### ISSUE TITLE
Images issue

### ISSUE THREAD

**Issue by roshanravan** [manhong2112/DownloadRedirect#1]
Is it supposed to work with saving images from firefox and chrome?
I have tested but saving image from either of them does not work
Catlog attached
[2016-07-21-18-06-39.txt](https://github.com/manhong2112/DownloadRedirect/files/376108/2016-07-21-18-06-39.txt)

**Comment by manhong2112** [comment]
Em...no, it doesn't suppose. Browser download images when they are loading a website. Saving image just copies images from cache but not a new download.
