### ISSUE TITLE
Whitelist doesn't work neither downloads from Firefox

### ISSUE THREAD

**Issue by marcelser** [manhong2112/DownloadRedirect#11]
Hi tried download redirect. But I doesn't really work. It captured downloads from Xposed installer, so I activated whitelist for apps and added xposed installer, but the downloads were still captured. On the other hand I wanted to download something in Firefox and nothing happened. Downloads didn't start at all. Not in system app, nor were they captured by download redirect. So I disabled this app. It seems it completely messes up downloading in marshmallow.

**Comment by BinoWassabi** [comment]
How to use this module can you explain pls

**Comment by manhong2112** [comment]
actually, firefox has their own downloader...and sorry i cannot give anymore support for this app bacause of time...
