### ISSUE TITLE
Same version code

### ISSUE THREAD

**Issue by KaMyKaSii** [manhong2112/DownloadRedirect#15]
You haven't increased version code. Then Xposed Installer believes that the module is updated even if it is not
![screenshot_20170401-200942](https://cloud.githubusercontent.com/assets/17092335/24583161/9e2df1f8-1717-11e7-8353-5e669096a34b.png)
![screenshot_20170401-200934](https://cloud.githubusercontent.com/assets/17092335/24583153/83d81090-1717-11e7-8d36-af7897f1e0e5.png)
![screenshot_20170401-200952](https://cloud.githubusercontent.com/assets/17092335/24583163/a70b2d5e-1717-11e7-9f9f-37f46db5c362.png)

**Comment by manhong2112** [comment]
ah...i remember the version code of 1.2.0 is 58......or maybe you installed the apk at release page?....

**Comment by KaMyKaSii** [comment]
I believe I have installed the apk of the release page.
