### ISSUE TITLE
Doesn't work on Android Nougat

### ISSUE THREAD

**Issue by briantyler7171** [manhong2112/DownloadRedirect#17]
I installed version 1.2.3 & 1.2.1 both keep crashing

**Comment by FingalZhou** [comment]
I got same problem. Actually it does work on Nougat, but the setting menu crashes every time when u try to open it, so u cannot set any blacklist or whitelist.

**Comment by manhong2112** [comment]
it is because MODE_WORLD_READABLE was deprecated in android n, i will fix it when official xposed for android n is released

**Comment by manhong2112** [comment]
Released new version, hopefully it can fix this problem...

**Comment by manhong2112** [comment]
if no update, then i just close this issues.
