### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by kamilmirza** [manhong2112/DownloadRedirect#2]
no Blacklisted apps LIST
plus Whitelist option is quite confusing 
there should be Whitelist and Blacklist option for allowing and disallowing apps and links 
works perfectly with ADM, kudos to that 👍

**Comment by manhong2112** [comment]
thank for support. you can list all blacklisted apps or links by clicking the text. also you can choose which of them to use whitelist by clicking "Use WhiteList".

**Comment by MacgyverJohnson** [comment]
Hi there @manhong2112 
Awesome app...working like a charm...
I still don't understand the blacklist and whitelist.....could you please have a separate blacklist for apps and links...for instance I want to add a browser to white list(chrome) but a link to blacklist(zippyshare.com)...how can i do that? can u give step by step instruction(screenshots are always helpful)

**Comment by manhong2112** [comment]
@MacgyverJohnson
think for support..

em...do you mean that you want to use it on chrome only, and ignore the download come from zippyshare?

if yes, here is the instruction, 
Press "Use WhiteList"
Check "App"
Back
Add ".*zippyshare\.com.*" to link list
Add Chrome to app list

**Comment by ashoksoni** [comment]
This doesn't work for me.

".*shaanig\.org.*"

How to keep using gello browser yet avoid adm to pick links from shaanig.org?

**Comment by ashoksoni** [comment]
Ok, please ignore last post. 

This worked.

.*shaanig\.org.*

**Comment by ashoksoni** [comment]
Adding .shaanig.org. doesn't work anymore, is this the right syntax?
