### ISSUE TITLE
It doesnt work on modded adm pro android 6.0.1

### ISSUE THREAD

**Issue by aaazv** [manhong2112/DownloadRedirect#22]
Hello, your xposed app its too useful, but I dont know why it doesnt work with the graphic modded adm pro which Ill give you the link:

http://www.dl.farsroid.com/app/Advanced-Download-Manager-Pro-6.3.1-Mod(FarsRoid.com).apk 

And Im already using your latest update 1.3.0.1

Thanks for your support.

**Comment by aaazv** [comment]
And by not working I mean keeps downloading with chrome

**Comment by aaazv** [comment]
it stragely worked on xposed installer when pressing download, but not when holding a pic in chrome and clicking download

**Comment by manhong2112** [comment]
module do not work on chrome and any other app which is using their own downloader.

**Comment by manhong2112** [comment]
em..if no update, then i just close the issues
