### ISSUE TITLE
Help file out support

### ISSUE THREAD

**Issue by Uninfallible** [manhong2112/DownloadRedirect#3]
I think a small help file or site, even something on Google+ would be extremely helpful. Especially a list of the apps settings, a description and a small explanation on how to use it.  The app is great, I love it.  But getting it set up is not self evident or obvious.  Thanks for the great work and awesome app!

(The time was supposed to be "Help File or Support".  Sorry for the typo)

**Comment by manhong2112** [comment]
Thanks for suggestion. i would add a help page in the app later, but i am not good at english so it may need some time.

**Comment by Uninfallible** [comment]
If you like I can look over whatever you may write and clean it up so it sounds correct.  Or you could even write it up in your native language and then I will put it through google or other translation app and then correct the grammar etc to make it correct.  Just a thought.

Thanks for the reply and love the app!

**Comment by Uninfallible** [comment]
If you like I can look over whatever you may write and clean it up so it
sounds correct.  Or you could even write it up in your native language and
then I will put it through google or other translation app and then correct
the grammar etc to make it correct.  Just a thought.

Thanks for the reply and love the app!
