### ISSUE TITLE
Not working on any of the chrome version

### ISSUE THREAD

**Issue by PallabKumarS** [manhong2112/DownloadRedirect#31]
Using latest download redirection but its not redirecting chrome dev download anymore...but before 1.2.1 update used to redirect..now i cant even use 1.2.1....its keeps closing when i try to open it...not  even 1.2.0 is opening..... And 1.3.1 is not working..

**Comment by paletteOvO** [comment]
Chrome has their own downloader now. It won't work with chrome anymore
