### ISSUE TITLE
not working on latest version of idmPro on my device (android 7.1) 

### ISSUE THREAD

**Issue by elswerky** [manhong2112/DownloadRedirect#32]
the module not working with me on andoid 7 
i use latest version of this module 
especially on chrome it doesn't work 

i was using an old version to make it work with me ,,, but i faced force close of the moduel using this old version ( v1.21 ) and also the old version wasn't working on chrome

**Comment by paletteOvO** [comment]
this module is not working on Chrome since they are using their own download manager now.

?~ manhong2112 (<?ω·)~☆kira

________________________________
