### ISSUE TITLE
NPE when booting

### ISSUE THREAD

**Issue by aviraxp** [manhong2112/DownloadRedirect#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:844)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at net.manhong2112.downloadredirect.XposedHook$parsePackageHook$1.afterHookedMethod(XposedHook.kt:114)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at android.content.pm.PackageParser.parsePackage(<Xposed>)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:6003)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.scanPackageLI(<Xposed>)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.scanDirLI(PackageManagerService.java:5860)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2300)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.<init>(<Xposed>)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:1868)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:386)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.SystemServer.run(SystemServer.java:288)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.server.SystemServer.main(SystemServer.java:175)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at java.lang.reflect.Method.invoke(Native Method)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-24 22:13:17.872 E/Xposed  ( 4828): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by manhong2112** [comment]
it seem that the result of parsePackage returned null although it is not supposed to do that. I will try to find out the reason later...
