### ISSUE TITLE
More support

### ISSUE THREAD

**Issue by KaMyKaSii** [manhong2112/DownloadRedirect#5]
Could add support for built-in download manager in Google Chrome? I do not know about the normal version, but at least Google Chrome Dev that use could not capture downloads so adding the app as a part of the link of a test site. And a topic in Xda would be better for users to interact, make suggestions and the like

**Comment by manhong2112** [comment]
it work on my phone with chrome dev...could you plz send me the logcat?

**Comment by KaMyKaSii** [comment]
http://pastebin.com/C6CD3X7b

If this logcat is not enough or you need a specific command, please tell me

**Comment by KaMyKaSii** [comment]
And here is the Xposed log:
http://pastebin.com/0Zjs4usg
I have disabled all other modules except your

**Comment by manhong2112** [comment]
ar...did you switch on debug logging in my app?

**Comment by KaMyKaSii** [comment]
Now yes
http://pastebin.com/Q8GyaQXk

**Comment by manhong2112** [comment]
could you send the full logcat and also download from chrome again for log down some infomation? And does it also not working at other app or only at chrome dev?

**Comment by KaMyKaSii** [comment]
In addition to the Chrome Dev the only app I tested was the XDA Labs and worked perfectly, because it uses the system's download manager, but the Chrome Dev seems to be a built-in itself, considering the name of the notification
https://drive.google.com/file/d/0B1uvONk-jlRiLWxiVnplV1RsT3c/view?usp=drivesdk

**Comment by manhong2112** [comment]
If chrome dev using built-in download manager, it would be hard to support and i think i won't be support a specific browser....
and i still can't see anything about my app in your log...how do you get the logcat? or have you using root to get the logcat?

**Comment by manhong2112** [comment]
ar..i found a way to solve it, just enable "enable-system-download-manager" in chrome://flags to force it download via system download manager..
