### ISSUE TITLE
连接过滤无效

### ISSUE THREAD

**Issue by Hzbeta** [manhong2112/DownloadRedirect#6]
使用chrome时，点击GitHub上的readme.md连接时会转到AMD下载，添加正则表达式^.*?\.(md)$过滤也不成功，同时在应用中过滤chrome也不行，希望可以解决这个bug
机型是Nexus6p，Android6.0.1

**Comment by Hzbeta** [comment]
好像是对Android原生自带的chrome不起作用，用其他浏览器可以过滤，希望作者可以解决这个问题

**Comment by manhong2112** [comment]
chrome本身就會莫名其妙的把一些不是下載的也發下載intent, 跟這應用沒關係...選擇以Chrome打開就好

**Comment by Hzbeta** [comment]
可是当我冻结Adm后，再点击view all of readme.md时可以正常打开啊，并没有下载的，解冻Adm后就会弹出下载

**Comment by manhong2112** [comment]
然而事實上，這應用是在觸發系統下載時才會進行處理，也就是說假如出現了跳轉，一定是觸發了下載
另外，試試把這應用在xposed installer中關掉看看，ADM保持解凍狀態，如果情況消失了，就把logcat發給我吧，記得打開應用中的輸出日志和啟用模塊。
對了，你手機只有裝Chrome這一個瀏覽器嗎？

**Comment by Hzbeta** [comment]
关闭这个模块后依然跳转到Adm，我重装Adm后发现是自己把打开方式设置为了Adm...
谢谢作者大大啦
