### ISSUE TITLE
Doesn't work in default browser (Gello) of cm13. 

### ISSUE THREAD

**Issue by ashoksoni** [manhong2112/DownloadRedirect#8]
Here is what I did. 

install module, reboot and added the app browser and download to app list. I even reinstalled adm but downloads are still going through the default browser.

**Comment by ashoksoni** [comment]
I will gladly upload logs if you want, just do let me know.

**Comment by manhong2112** [comment]
app list is using blacklist in default, did you enable whitelist?, also does it has own downloader? it won't work with custom downloader

**Comment by ashoksoni** [comment]
Yes, I whitelist apps. It uses syatem downloader, doesn't have any custom one.

**Comment by manhong2112** [comment]
em...i tested it on my phone and it works (the newest one from apkmirror)... so i think i need to look at the log....

**Comment by ashoksoni** [comment]
Can you send me the link of apkmirror for that apk, I'll check with mine. I
am using it on marshmallow though just for the info and I'll gladly provide
the logs once I check the link of that apk.

Xposed or usual system logs?

**Comment by ashoksoni** [comment]
Ok, I checked apk for gello on apkmirror and it's the same one so I tested with chrome and it's fine there but not in gello with the same settings. I enabled logging in the app but xposed log didn't show anything related to it so do you need normal logs or any suggestion?

**Comment by ashoksoni** [comment]
This is I get when I try to download through gello browser. 

https://postimg.org/image/vaq5pizo7/

**Comment by manhong2112** [comment]
just click download button and it will redirect to adm

**Comment by ashoksoni** [comment]
Ah..  Yes, just got that before coming here to report. I don't suppose that it's possible to avoid this dialog and get adm directly, right? Even if it isn't, I will appreciate. Thanks again. ☺️

**Comment by manhong2112** [comment]
ah..it redirect after browser added it to download list, so the dialog can't be avoided :)

**Comment by ashoksoni** [comment]
Every setting is same, in fact restored the app and data from titanium backup as it is and yet it now doesn't work for any of my added file. What could be the issue?

**Comment by ashoksoni** [comment]
I actually had to reflash my phone again so had to setup everything again and this modules not working is messing up my setup.

**Comment by ashoksoni** [comment]
Even removed and install clean and setup up again. Whitelist app and then add two apps. Xposed installer and gello browser but not working in both.

**Comment by manhong2112** [comment]
ar...maybe you can try a older version?

**Comment by ashoksoni** [comment]
I added a wrongly formatted link to blacklist, all good now.
